local C = require("dark-moon.colors")

local M = {}

M.get = function ()
  return {
    -- See :help highlight-groups
    ColorColumn = { bg = C.bg.light },
    Conceal = {},
    Cursor = { fg = C.bg.dark, bg = C.yellow.base },
    CurSearch = {},
    lCursor = {},
    CursorIM = {},
    CursorColumn = {},
    CursorLine = { bg = C.bg.base },
    Directory = { fg = C.blue.base },
    DiffAdd = { fg = C.green.base },
    DiffChange = { fg = C.yellow.base },
    DiffDelete = { fg = C.red.base },
    DiffText = { fg = C.blue.base },
    EndOfBuffer = { fg = C.bg.dark, bg = C.bg.dark },
    TermCursor = { fg = C.bg.dark, bg = C.white },
    TermCursorNC = {},
    ErrorMsg = { fg = C.red.base },
    VertSplit = { fg = C.bg.base, bg = C.bg.dark },
    Folded = { fg = C.fg.dark },
    FoldColumn = { fg = C.yellow.base },
    SignColumn = { fg = C.yellow.base },
    IncSearch = { fg = C.bg.base, bg = C.yellow.base },
    Substitute = { fg = C.bg.base, bg = C.blue.base },
    LineNr = { fg = C.fg.dark },
    LineNrAbove = {},
    LineNrBelow = {},
    CursorLineNr = { fg = C.fg.base },
    CursorLineFold = {},
    CursorLineSign = {},
    MatchParen = { fg = C.cyan.base },
    ModeMsg = {},
    MsgArea = {},
    MsgSeparator = {},
    MoreMsg = {},
    NonText = {},
    Normal = { fg = C.fg.light, bg = C.bg.dark },
    NormalFloat = { bg = C.bg.dark },
    FloatBorder = { fg = C.bg.light },
    FloatTitle = { fg = C.fg.light, bg = C.bg.dark },
    NormalNC = {},
    Pmenu = { fg = C.fg.light, bg = C.grey.dark },
    PmenuSel = { fg = C.bg.lighter, bg = C.cyan.base },
    PmenuKind = {},
    PmenuKindSel = {},
    PmenuExtra = {},
    PmenuExtraSel = {},
    PmenuSbar = { bg = C.bg.lighter },
    PmenuThumb = { bg = C.fg.base },
    Question = {},
    QuickFixLine = {},
    Search = { bg = C.hollow.base },
    SpecialKey = { bg = C.bg.light },
    SpellBad = { sp = C.red.base, undercurl = true },
    SpellCap = { sp = C.yellow.base, undercurl = true },
    SpellLocal = { sp = C.orange.base, undercurl = true },
    SpellRare = { sp = C.blue.base, undercurl = true },
    StatusLine = {},
    StatusLineNC = {},
    TabLine = { fg = C.fg.light, bg = C.bg.dark },
    TabLineFill = { fg = C.fg.light, bg = C.bg.dark },
    TabLineSel = { fg = C.bg.dark, bg = C.cyan.base },
    Title = { fg = C.green.base },
    Visual = { bg = C.hollow.lighter },
    VisualNOS = { bg = C.hollow.lighter },
    WarningMsg = { fg = C.yellow.base },
    Whitespace = { bg = C.yellow.base },
    WinSeparator = { fg = C.bg.base },
    WildMenu = {},
    WinBar = {},
    WinBarNC = {},
    healthError = {},
    healthSuccess = {},
    healthWarning = {},
    healthHelp = {}
  }
end

return M
